---
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        stages:
          - pre-commit
        language: system
        entry: tools/check-format
        types_or:
          - c
          - c++
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: '^(\.gitlab-ci.yml|ci/)'
        args:
          - -c
          - ci/.yamllint.yml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
        exclude: '.vscode'
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        exclude: '^(\.gitlab-ci.yml|ci/)'
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: 'tools/qm35/JLinkDevices.patch'
      - id: trailing-whitespace
        exclude: 'tools/qm35/JLinkDevices.patch'
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
    - id: cmake-lint
